### PR TITLE
Cleaned up the code.

### PR DESCRIPTION
**Pull request by KleinerNull**
Cleaned up the input validation. Breaks after the try block is succesful. No need for continue after a real expression like print in the except block.

Also no need to loop over a multipled list, Use range(x) instead and the _ is the convention for an unused loop variable.

Also, you never used itertools, deleated that import.

Code should work for both major python versions.

Also deleted that useless instances of webs and num.

Also use a docstring now instead of printing out countless other variables.

### CODE REVIEW

**Comment by JackCDK** [comment]
Hey I tried your changes in python3/2 and it just hangs after typing in a number in python3 and in python2 it just says:

   ```
website = input("[?] What site do you want to use?:")
   File "<string>", line 1, in <module>
   NameError: name 'www' is not defined
```

Thanks for cleaning up the code anyway, I really needed that haha I will sometimes use code with tons of junk code inside which I don't really need but I don't notice so I just continue.

**Comment by KleinerNull** [comment]
Oh this is a py3/py2 thing I forgot about it:

Python2 | Python 3
---------|----------
input | --- # doesn't exist any more
raw_input | input

You could something like:

    try:
        input = raw_input # for python 2
    except NameError:
        pass   # nothing happends in python 3

    ...
    user_input = input('Bla bla bla') # now the right version should be used

**Comment by JackCDK** [comment]
Yeah in v1.0.5 of the tool I had this

```
try: input = raw_input
except NameError: pass
```

It would make things a lot easier to just have one main tool.

**Comment by KleinerNull** [comment]
Got rid of the structure

Git is a tool for version control, it will save every commit and you could go to any point of your code history. Just change your file and the history is saved. That's the whole point of git.

Added a variable called `__version__ ` you can change this value to keep track of your version number.

**Comment by JackCDK** [comment]
I did not know most of this, I'm pretty new to git, thanks for informing me about this!

**Pull request closed without merging**
